# kubectl create secret generic kube-config --from-file=kube_config/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flint
  labels:
    app: flint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flint
  template:
    metadata:
      labels:
        app: flint
    spec:
      restartPolicy: Always
      volumes:
        - name: flint-conf-storage
          configMap:
            name: ${config_map_name}
        - name: data-storage
          persistentVolumeClaim:
            claimName: ${nfs_pvc_name}
      containers:
        - name: flint
          image: ${flint_image_name}
          volumeMounts:
            - mountPath: /etc/mysql/my.cnf
              name: flint-conf-storage
              subPath: my.cnf
            - mountPath: /var/lib/mysql
              name: data-storage
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512M
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flint-service
spec:
  ports:
    - name: client
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: flint
  type: NodePort