apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: ${nfs_image_name}
          securityContext:
            privileged: true
          env:
            - name: NFS_DIR
              value: /nfs/share
            - name: NFS_OPTION
              value: "fsid=0,rw,sync,insecure,no_root_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide"
          volumeMounts:
            - name: nfs-share
              mountPath: /nfs/share
      volumes:
        - name: nfs-share
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: rpcbind
      port: 111
      protocol: TCP
      targetPort: 111
  selector:
    app: nfs-server
  type: ClusterIP
